### ISSUE TITLE
c1 and c2 are assumed to be strings

### ISSUE THREAD

**Issue by thisisaaronland** [openvenues/lieu#2]
Flagging this as either a gotcha or a documentation issue. The whitespace regular expressions in `component_equals` assume input that can be `lower` -ed which make Python sad when passed integers.

I am re-running my code with input that is explicitly cast as `unicode` thingies so maybe that will fix the problem. It's not clear to me if this is a thing that should be handled in code or as part of strict input requirements/validation...

```
/usr/local/bin/dedupe_geojson *.bz2
TF-IDF index file: deduped/tfidf.index
Near-dupe tempfile: deduped/near_dupes
Guids DB: deduped/guids_db
Output filename: deduped/deduped.geojson
-----------------------------
* Assigning IDs, creating near-dupe hashes + IDF index
* Sorting temporary near-dupe file by hash
* Checking blocks of near-dupe candidates pairwise for dupes
Traceback (most recent call last):
  File "/usr/local/bin/dedupe_geojson", line 181, in <module>
    name_dupe_threshold=name_dupe_threshold, with_unit=with_unit)
  File "/usr/local/lib/python2.7/dist-packages/lieu/dedupe.py", line 174, in is_dupe
    same_address = cls.is_address_dupe(a1, a2)
  File "/usr/local/lib/python2.7/dist-packages/lieu/dedupe.py", line 49, in is_address_dupe
    same_house_number = cls.component_equals(a1_house_number, a2_house_number, ADDRESS_HOUSE_NUMBER)
  File "/usr/local/lib/python2.7/dist-packages/lieu/dedupe.py", line 22, in component_equals
    if no_whitespace and whitespace_regex.sub(u'', c1.lower()) == whitespace_regex.sub(u'', c2.lower()):
AttributeError: 'int' object has no attribute 'lower'
```

**Comment by thatdatabaseguy** [comment]
There are a couple of unpushed changes that I'm testing now, but aware of this and have already addressed it.
