### ISSUE TITLE
local variable 'house_number_sim' referenced before assignment

### ISSUE THREAD

**Issue by thisisaaronland** [openvenues/lieu#5]
Running from the command line on a local machine

```
python ./scripts/dedupe_geojson -o . file-1 file-2

did 162670000 hashes requiring 17251839 pairwise comparisons
did 162680000 hashes requiring 17252606 pairwise comparisons
did 162690000 hashes requiring 17252938 pairwise comparisons
did 162700000 hashes requiring 17253194 pairwise comparisons
Traceback (most recent call last):
  File "./scripts/dedupe_geojson", line 420, in <module>
    is_dupe = dupe_func(canonical, other, dupe_pairs, dupes, **dupe_func_kw)
  File "./scripts/dedupe_geojson", line 113, in is_name_address_dupe
    fuzzy_street_name=fuzzy_street_names)
  File "/usr/local/lib/python2.7/site-packages/lieu/dedupe.py", line 388, in dupe_class_and_sim
    same_address = cls.is_address_dupe(a1, a2, languages=languages, fuzzy_street_name=fuzzy_street_name)
  File "/usr/local/lib/python2.7/site-packages/lieu/dedupe.py", line 126, in is_address_dupe
    dupe_class, sim = cls.address_dupe_status(a1, a2, languages=languages, fuzzy_street_name=fuzzy_street_name)
  File "/usr/local/lib/python2.7/site-packages/lieu/dedupe.py", line 116, in address_dupe_status
    return min((street_status, street_sim), (house_number_status, house_number_sim))
UnboundLocalError: local variable 'house_number_sim' referenced before assignment
```

**Comment by thisisaaronland** [comment]
Fixed, thanks.
