### ISSUE TITLE
TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by thisisaaronland** [openvenues/lieu#8]
When running:

```
/usr/local/bin/dedupe_geojson --no-latlon -o . file1.geojson file2.geojson

Traceback (most recent call last):
  File "/usr/local/bin/dedupe_geojson", line 316, in <module>
    hashes = NameAddressDeduper.near_dupe_hashes(address, with_latlon=use_latlon, with_address=with_address, with_city_or_equivalent=use_city, with_small_containing_boundaries=use_containing, with_postal_code=use_postal_code, with_zip5=use_zip5, name_and_address_keys=with_address, name_only_keys=name_only)
  File "/usr/local/lib/python2.7/site-packages/lieu/dedupe.py", line 285, in near_dupe_hashes
    all_hashes.extend([h for h in hashes if h not in all_hashes_set])
TypeError: 'NoneType' object is not iterable
```

**Comment by thisisaaronland** [comment]
Oh, this might be because am I feeding it a `FeatureCollection` and not line-separated GeoJSON. One moment please...

**Comment by thisisaaronland** [comment]
My bad.

**Comment by Eric-Arellano** [comment]
I'm getting this error with the following input and running `--no-latlon`. Any ideas what might be happening?

**Comment by braco** [comment]
These are maddeningly inscrutable error messages, how did you guys even figure out why it was throwing that?
